<?php
$_form = $this;
$_code = $_form->getMethodCode();
$_model = Mage::getModel('braintree/paymentMethod');
$_method = $_form->getMethod();
?>
<script type="text/javascript">
    payment.form = 'co-braintree-form';
</script>
<input id="<?php echo $_code ?>_payment_method" type="hidden" name="payment[method]" value="<?php echo $_code ?>" />
<ul id="payment_form_<?php echo $_code ?>" class="form-list">
    <li>
        <label for="<?php echo $_code ?>_cc_type" ><?php echo $this->__('Credit Card Type') ?><span class="required">*</span></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--')?></option>
            <?php $_ccType = $_form->getInfoData('cc_type') ?>
            <?php foreach ($_form->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?><span class="required">*</span></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]"  data-encrypt="true" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" ><?php echo $this->__('Expiration Date') ?><span class="required">*</span></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
            <?php $_ccExpMonth = $_form->getInfoData('cc_exp_month') ?>
            <?php foreach ($_form->getCcMonths() as $k=>$v): ?>
                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $_form->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
            <?php foreach ($_form->getCcYears() as $k=>$v): ?>
                <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
            <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php echo $_form->getChildHtml() ?>
    <?php if($_form->hasVerification()): ?>
    <li id="<?php echo $_code ?>_cc_type_cvv_div">
        <label for="<?php echo $_code ?>_cc_cid" ><?php echo $this->__('Card Verification Number') ?><span class="required">*</span></label>
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" data-encrypt="true" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
            </div>
            <a href="#" id="braintree-cvv-what-is-this" style="cursor:help; margin-left:5px;"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
</ul>
<script type="text/javascript">
//<![CDATA[
document.observe('dom:loaded', function () {
  braintree_adminhtml_init('<?php echo $_model->getConfigData('client_side_encryption_key') ?>');

  // Prevent adminhtml order form from posting CC data back to server for validations
  AdminOrder.prototype.prepareParams = function(params) {
    if (!params) {
      params = {};
    }
    if (!params.customer_id) {
      params.customer_id = this.customerId;
    }
    if (!params.store_id) {
      params.store_id = this.storeId;
    }
    if (!params.currency_id) {
      params.currency_id = this.currencyId;
    }
    if (!params.form_key) {
      params.form_key = FORM_KEY;
    }

    if (this.paymentMethod != '<?php echo $_code ?>') {
      var data = this.serializeData('order-billing_method');
      if (data) {
        data.each(function(value) {
          params[value[0]] = value[1];
        });
      }
    } else {
      params['payment[method]'] = '<?php echo $_code ?>';
    }
    return params;
  };

  AdminOrder.prototype.getPaymentData = function(currentMethod) {
    if (typeof (currentMethod) == 'undefined') {
      if (this.paymentMethod) {
        currentMethod = this.paymentMethod;
      } else {
        return false;
      }
    }
    if (currentMethod == '<?php echo $_code ?>') {
      return false;
    }
    var data = {};
    var fields = $('payment_form_' + currentMethod).select('input', 'select');
    for ( var i = 0; i < fields.length; i++) {
      data[fields[i].name] = fields[i].getValue();
    }
    if ((typeof data['payment[cc_type]']) != 'undefined'
        && (!data['payment[cc_type]'] || !data['payment[cc_number]'])) {
          return false;
        }
        return data;
  };

});
//]]></script>
