<head>
<style>
body,td { color:#2f2f2f; font:11px/1.35em Verdana, Arial, Helvetica, sans-serif; }
</style>
</head>
<body style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<div style="background:#F6F6F6; font-family:Verdana, Arial, Helvetica, sans-serif; font-size:12px; margin:0; padding:0;">
<table cellspacing="0" cellpadding="0" border="0" width="100%">
<tr>
    <td align="center" valign="top" style="padding:20px 0 20px 0">
        <table bgcolor="#FFFFFF" cellspacing="0" cellpadding="10" border="0" width="650" style="border:1px solid #E0E0E0;">
            <!-- [ header starts here] -->
            <tr>
                <td valign="top"><img src="{{var logo_email}}" style="margin-bottom:10px;" border="0"/></td>
            </tr>
            <!-- [ middle starts here] -->
            <tr>
                <td valign="top">
                    <h1 style="font-size:22px; font-weight:normal; line-height:22px; margin:0 0 11px 0;"">{{var email_header}}.</h1>
                    <p style="font-size:12px; line-height:16px; margin:0;">{{var email_message}}</p>
            </tr>
            <tr>
                <td>
                    <h2 style="font-size:18px; font-weight:normal; margin:0;">Your Order #{{var order.increment_id}} <small>(placed on {{var order.getCreatedAtFormated('long')}})</small></h2>
                </td>
            </tr>
            <tr>
                <td>
                    <table cellspacing="0" cellpadding="0" border="0" width="650">
                        <thead>
                        <tr>
                            <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Billing Information:</th>
                            <th width="10"></th>
                            <th align="left" width="325" bgcolor="#EAEAEA" style="font-size:13px; padding:5px 9px 6px 9px; line-height:1em;">Shipping Information:</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td valign="top" style="font-size:12px; padding:7px 9px 9px 9px; border-left:1px solid #EAEAEA; border-bottom:1px solid #EAEAEA; border-right:1px solid #EAEAEA;">
                                {{var order.getBillingAddress().format('html')}}
                            </td>
                            <td>&nbsp;</td>
                            <td valign="top" style="font-size:12px; padding:7px 9px 9px 9px; border-left:1px solid #EAEAEA; border-bottom:1px solid #EAEAEA; border-right:1px solid #EAEAEA;">
                                {{var order.getShippingAddress().format('html')}}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
            	<td>
            		<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
					    <tr>
					        <td align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px" width="330"><strong><?php echo Mage::helper('adminhtml')->__('Product Name')?></strong></td>
					        <td align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><strong><?php echo Mage::helper('adminhtml')->__('Details')?></strong></td>
					        <td align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px" width="100"><strong><?php echo Mage::helper('adminhtml')->__('SKU')?></strong></td>
					        <td align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px" width="50"><strong><?php echo Mage::helper('adminhtml')->__('Quantity')?></strong></td>
					    </tr>
					    {{var email_items}}
					</table>
            	</td>
            </tr>
        </table>
    </td>
</tr>
</table>
</div>
</body>