<?php 
    $sections = $this->getSaleSections(); 
?>
 
								
 
<?php $i=0; ?>
<?php $opening_sales = $this->getSales( $sections['openining']['interval'] ); ?>
<?php $no_sales = $opening_sales->count(); print $no_sales;
      $first_column_sales = ceil($no_sales/2);
 ?>
<?php $counter = 1; ?>
<?php foreach($sales_categories as $sale): ?>
    <?php if($counter > 4) break; ?>
    <?php if ($counter == 1 || $counter == $first_column_sales): ?>
 
        <?php if($counter == $first_column_sales): ?>
            </td>
            <td> </td>
        <?php endif; ?>
        <td align="center" valign="top" width="234">
        <?php if($counter == 1): ?>
            <font face="georgia" size="+2" color="#966987"><em>Open it to discover</em></font><br /><br />
        <?php endif; ?>
    <?php endif; ?>
    
            <a href="<?php echo $sale->getUrl(); ?>" title="<?php echo $sale->getName(); ?>">
            <img alt="<?php echo $sale->getName(); ?>" border="0" height="193" src="<?php echo $this->getResizedImage($sale, 234, 193);  ?>" style="display:block" width="234" /></a><br />
            <a href="<?php echo $sale->getUrl(); ?>" title="<?php echo $sale->getName(); ?>">
			    <font face="verdana" size="-1" color="#7f767e"><?php echo $sale->getName(); ?><br />
			    JEWELRY DESIGNS</font></a><br /><br />
			    
			<font face="georgia" size="+0" color="#966987"><em>by <strong><a href="<?php echo $sale->getUrl(); ?>"><?php echo $sale->getName(); ?></a></strong></em></font>
			<?php if($counter == 1 || $counter == 3): ?>
			    <br />
			    <br />
			    <br />
            <?php endif; ?>
            <?php if ($counter == $no_sales): ?>
                <br />
				<br />
				
				<img alt="red line" border="0" height="4" src="http://test.wonderhop.com/skin/frontend/wonderhop/default/images/newsletter/daily/red_line.png" style="display:block" width="228" />
				<font face="georgia" size="+2" color="#fd706b"><em>and much more!</em></font>					
            <?php  endif; ?>
    <?php $counter++; ?>
<?php endforeach; ?>
        </td>
        <td width="10"> </td>
    </tr>
</table>
