<?php

$colls_cat_id = (int)(string)Mage::getConfig()->getNode('localconf/modules/catalog/category/collections_cat_id');
$colls_cat = Mage::getModel('catalog/category')->load($colls_cat_id);

$sections = explode(',', (string)$colls_cat->getChildren());


// we have two sections in the menu
//  - by type
//  - by brand

$menu = array(
    'type' => array(
        'title' => 'Shop by<br/>category',
        'children' => array(),
    ),
    
    'wedding' => array(
        'title' => 'Shop<br/>Wedding',
        'children' => array(),
    ),
    
    'style' => array(
        'title' => 'Shop by<br/>style',
        'children' => array(),
    ),
    'brand' => array(
        'title' => 'Shop by<br/>brand',
        'children' => array(),
    ),
    
);


foreach($sections as $section_id)
{
    $section = Mage::getModel('catalog/category')->load((int)$section_id);
    if ($section->getName() == 'Category' )
    {
        $sec_menu = &$menu['type'];
    }
    elseif ($section->getName() == 'Brand')
    {
        $sec_menu = &$menu['brand'];
    }
    elseif ($section->getName() == 'Style')
    {
        $sec_menu = &$menu['style'];
    }
    elseif ($section->getName() == 'Wedding')
    {
        $sec_menu = &$menu['wedding'];
    }
    
    $children = (string)$section->getChildren();
    if ( ! $children) continue;
    
    $prims = explode( ',' , $children);
    foreach($prims as $prim_id)
    {
        $prim = Mage::getModel('catalog/category')->load((int)$prim_id);
        
        $menu_item = array(
            'title' => $prim->getName(),
            'url' => Mage::getBaseUrl() . $prim->getUrlPath(),
            'children' => array(),
        );
        
        $prim_children = (string)$prim->getChildren();
        if ($prim_children)
        {
            $secs = explode( ',' , $prim_children);
            foreach($secs as $sec_id)
            {
                $sec = Mage::getModel('catalog/category')->load((int)$sec_id);
                $sec_item = array(
                    'title' => $sec->getName(),
                    'url' => Mage::getBaseUrl() . $sec->getUrlPath(),
                    'children' => array(),
                );
            
                $menu_item['children'][$sec->getPosition()] = $sec_item;
            }
            ksort($menu_item['children']);
        }
        
        $sec_menu['children'][$prim->getPosition()] = $menu_item;
        ksort($sec_menu['children']);
    }

}

//echo '<pre>';
//var_dump($menu);
//echo '</pre>';
?>
<ul id ="sidebar_nav" class="sidebar-nav level0">
<?php foreach($menu as $top) { ?>
        
    <li class="sidebar-nav-heading"><h4><?php echo $top['title']; ?></h4></li>
    <?php if ($top['children']) { ?>

    <li class="sidebar-nav-children">
        <ul class="sidebar-nav level1">
        <?php foreach($top['children'] as $child) { ?>
            
            <li class="sidebar-nav-heading"><a href="<?php echo $child['url']; ?>"><?php echo $child['title']; ?></a></li>
            <?php if ($child['children']) { ?>
                
                <li class="sidebar-nav-children">
                    <ul class="sidebar-nav level2">
                    <?php foreach($child['children'] as $sub) { ?>
                        <li class="sidebar-nav-heding"><a href="<?php echo $sub['url']; ?>"><?php echo $sub['title']; ?></a></li>
                    <?php } ?>
                    </ul>
                </li>
            
            <?php } ?>
            
        <?php } ?>
        </ul>
    </li>
    
    <?php } ?>
    
<?php } ?>
</ul>
