<?php




$outputHelper = $this->helper('catalog/output');
$product = $this->getProduct();
$category = $this->getCAtegory();
$width  = 430;
$height = 400;
$price = '$'.number_format($product->getSpecialPrice() ? $product->getSpecialPrice() : $product->getPrice(), 0);

if ($product) {
?>
<div class="randprod-heading-wrap">
    <div class="randprod-heading">
        <h1>The Gift Explorer</h1>
    </div>
</div>
<div class="randprod-wrap">
    <div class="randprod-nav-wrap">
        <!--<a class="rendprod-prev" href="#" onclick="history.go(-1);return false;">Previous</a> -->
        <a class="randprod-next" href="#" onclick="setLocation('<?php echo $this->helper('core/url')->getCurrentUrl(); ?>');return false;">View another product</a>
    </div>
    <a href="<?php echo $product->getProductUrl(); ?>" class="randprod single">
        <div class="randprod-text">
            <h1><?php echo $product->getName() . '&nbsp;&mdash;&nbsp;' . $price; ?></h1>
        </div>
        <div class="randprod-image">
            <?php
            $_img = '<img src="'.$this->helper('catalog/image')->init($product, 'image')->resize(null,$height).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
            echo $outputHelper->productAttribute($product, $_img, 'image');
            ?>
        </div>
    </a>
    <form class="randprod-under-wrap" id="product_addtocart_form">
        <div class="randprod-addtocart">
        <?php
            if ( ! Mage::registry('product')) Mage::register('product', $product);
            $addtocart = $this->getLayout()->createBlock('catalog/product_view', 'r_addtocart', array(
                    'template' => 'catalog/product/view/addtocart.phtml'));
            echo $addtocart->toHtml();
            ?>
        </div>
        <div class="randprod-desc-wrap">
            <div class="randprod-desc">
                <?php echo nl2br($product->getDescription()); ?>
            </div>
        </div>
    </form>
    <script type="text/javascript">
        (function($){
            var $form = $('#product_addtocart_form'), $button = $form.find('button'), $qty = $form.find('input[type="text"]');
            $button.attr('onclick','').click(function(ev){ 
                ev.preventDefault();
                $form.submit();
                return false;
            });
            $form.attr('method', 'post').attr('action' , '/checkout/cart/add/product/<?php echo $product->getId(); ?>');
            /*$form.submit(function(ev){
                ev.preventDefault();
                var qty = parseInt($qty.val()) ? parseInt($qty.val()) : 1;
                jQuery.post('/checkout/cart/add/product/<?php echo $product->getId(); ?>?qty='+qty,function(data){
                    setLocation('/checkout/cart');
                });
                return false;
            });*/
            parseInt($qty.val()) || $qty.val(1);
        })(jQuery);
    </script>
</div>
<?php
}
