<?php




$outputHelper = $this->helper('catalog/output');
$product = $this->getProduct();
$category = $this->getCAtegory();
$width  = 430;
$height = 400;
$price = '$'.number_format($product->getSpecialPrice() ? $product->getSpecialPrice() : $product->getPrice(), 0);

if ($product) {
?>

<div class="randprod-wrap">
    <div class="randprod-nav-wrap">
        <!--<a class="rendprod-prev" href="#" onclick="history.go(-1);return false;">Previous</a> -->
        <a class="randprod-next" href="#" onclick="setLocation('<?php echo $this->helper('core/url')->getCurrentUrl(); ?>');return false;">View another product</a>
    </div>
    <a href="<?php echo $product->getProductUrl(); ?>" class="randprod single">
        <div class="rendprod-text">
            <h1><?php echo $product->getName() . '&nbsp;&mdash;&nbsp;' . $price; ?></h1>
        </div>
        <div class="randprod-image">
            <?php
            $_img = '<img src="'.$this->helper('catalog/image')->init($product, 'image')->resize(null,$height).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
            echo $outputHelper->productAttribute($product, $_img, 'image');
            ?>
        </div>
    </a>
</div>
<?php
}
