<div class="header-usermenu-graphic"></div>
<ul class="header-usermenu">
    <li><a href="<?php echo $this->getUrl('customer/account'); ?>">My Account</a></li>
    <li><a href="<?php echo $this->getUrl('sales/order/history'); ?>">My Orders</a></li>
    <li><a href="<?php echo $this->getUrl('customercredit'); ?>">My Credit</a></li>
    <?php $logoutUrl = $this->getUrl('customer/account/logout'); ?>
    <li><a href="javascript:void(0);" onclick="doAjaxAndRedirect({url:'<?php echo $logoutUrl; ?>'}, '/collection', 1100);">Log Out</a></li>
</ul>
<script type="text/javascript">decorateGeneric($$('.header-usermenu li'), ['first','last']);</script>
