<?php
    
    $session = Mage::getSingleton('customer/session');
    $giftcard = $this->getGiftcard();
?>
<div id="gift_message_form" class="giftcard" method="post">
    <ul class="form-list">
        
        <li>
            <div class="input-box">
                <label for="giftcard_ammount">Giftcard Credit <small>(USD)</small><span class="required">*</span>:</label>
                <input name="giftcard_ammount" class="input-text" value="<?php echo $session->getGiftcardAmmount() ? $session->getGiftcardAmmount() : 50; ?>" />
            </div>
        </li>
        <li>
            <div class="input-box">
                <label for="gift_to_email">Recipient Email <span class="required">*</span>:</label>
                <input name="gift_to_email" class="input-text" value="<?php echo $session->getGiftToEmail(); ?>" />
            </div>
        </li>
        <li>
            <div class="input-box half left">
                <label for="gift_from_text">From <small>(your name)</small>:</label>
                <input name="gift_from_text" class="input-text" value="<?php echo $session->getGiftFromText() ? $session->getGiftFromText() : ${($session->setGiftFromText($customer_name) or 1)?'customer_name':1}; ?>" />
            </div>
            <div class="input-box half left tweak">
                <label for="gift_to_text">To <small>(your friend's name)</small>:</label>
                <input name="gift_to_text" class="input-text right" value="<?php echo $session->getGiftToText(); ?>" />
            </div>
        </li>
        <li>
            <label for="gift_message_text">Include a note <small>(optional)</small></label>
            <textarea name="gift_message_text" class="input-text"><?php echo $session->getGiftMessageText(); ?></textarea>
        </li>
        <li class="action">
            <button class="button checkout-btn" onclick="buyGiftcard();"><span><span>Send Giftcard Now ! </span></span></button>
        </li>
    </ul>
</div>

<script type="text/javascript">
    (function($){

        var $form = $('#gift_message_form').parents('form').first(), $fields = $form.find('.form-list');
        var $buyGiftcard = function (){
            var $email = $fields.find('[name="gift_to_email"]'), email = $email.val(), is_email = /^[a-z0-9\-\+_\.]{3,}@[a-z][a-z0-9\-]+\.[a-z]{2,4}$/i;
            if ( ! is_email.test(email)) {
                $email.addClass('validation-failed');
                if ( ! $email.next().hasClass('validation-advice')) {
                    $email.after('<span class="validation-advice">Please enter a valid email address!</span>');
                }
                return false;
            } else {
                $email.removeClass('validation-failed');
                if ( ! $email.next().hasClass('validation-advice')) {
                    $email.next().fadeOut(function(){ $(this).remove(); });
                }
            }
            var $amm = $fields.find('[name="giftcard_ammount"]'), amm = $amm.val(), is_amm = function(amm){ return /^[\d]+$/.test(amm) && parseInt(amm) > 10 && parseInt(amm) < 100; };
            if ( ! is_amm(amm)) {
                $amm.addClass('validation-failed');
                if ( ! $amm.next().hasClass('validation-advice')) {
                    $amm.after('<span class="validation-advice">Please enter a number between 10 and 1000!</span>');
                }
                return false;
            } else {
                $email.removeClass('validation-failed');
                if ( ! $amm.next().hasClass('validation-advice')) {
                    $email.next().fadeOut(function(){ $(this).remove(); });
                }
            }
            setLocation('/sales/index/preparebuygiftcard?'+$form.serialize());
        };
        var buyGiftcard = function(){
            setTimeout($buyGiftcard, 500);
        };
        window.buyGiftcard = buyGiftcard;
        
        //var checkReady = function()
        /*
        formhooks.saving =  function(){
            $form.find('button').after('<span class="gmsg-saved" style="color:green;display:none;margin-left:10px;font-size:13px;">Message Saved!</span>');
            var $msg = $form.find('.gmsg-saved');
            $msg.fadeIn().delay(2000).fadeOut(function(){ $(this).remove(); 
            });
        }
        $switch.change(function(){
            $fields['fade'+($(this).is(':checked') ? 'In' : 'Out')]();
            $.post(
                '/sales/index/savegmsg',
                $form.serialize() + ( ! $(this).is(':checked') ? '&gift_is_gift=0' :''), 
                function(data){}
            );
        });
        if ($switch.is(':checked')) $fields.fadeIn() && (Add_Gift = true);
        $form.submit(function(ev){
            ev.preventDefault();
            $.post(
                '/sales/index/savegmsg',
                $form.serialize(), 
                function(data) { $.each(formhooks, function(k,hook){
                    if ( ! hook) return false;
                    var _hook = (typeof hook == 'function') ? hook : Function(hook);
                    _hook.call($form);
                }); }
            );
            return false;
        });
        $(function(){
            var $checkout = $('.btn-checkout'), onclickFunc = $checkout.attr('onclick');
            $checkout.attr('onclick','');
            $('.btn-checkout').click(function(ev){
                ev.preventDefault();
                ev.stopPropagation();
                delete formhooks['saving'];
                formhooks.redirect = onclickFunc;
                $form.submit();
            });
        });
        window.formhooks = formhooks;*/
    })(jQuery);
</script>
