<?php if ($this->getCustomer()->getEmailConfirmation()): ?>
    <div class="message error">To get your reward credits please confirm your email.</div>
<?php endif; ?>


<?php 

// All sections

$sections = $this->getSaleSections(); 
extract($sections);


//
// Opening Shops
//

extract($opening);
$sales_categories = $this->getSales( $interval );

if ( ! empty($sales_categories) and count($sales_categories)) {
    
    $left = '';
    $right = '';
    $current = 'left';
    $counter = 0;
    
    foreach($sales_categories as $sale) {
        if(isset($interval['today'])) {
            $to_time = strtotime($sale->getEndDate());
            $from_time = strtotime($sale->getStartDate());
            
            if(round(abs($to_time - $from_time) / 3600,2) > 24 && $sale->getEndDate() < date("Y-m-d 23:59:59", Mage::getModel('core/date')->timestamp(time()))) {
                continue;
            }
        }
        ob_start();
        ?>

        <li class="sale-wrap">
            <div class="sale">
                <?php
                list($img_width,$size) = (($counter%4 == 0) or ($counter%4 == 3)) ? array(330,1) : array(410,2);
                list($current,$not_current) = ($counter%2 == 0) ? array('left','right') : array('right','left');
                ?>
                <?php if($sale->getThumbnail()) { ?>
                    <a class="sale_image" href="<?php echo $sale->getUrl(); ?>" title="<?php echo $sale->getName(); ?>">
                        <img alt="<?php echo $sale->getName(); ?>" src="<?php echo $this->getResizedImage($sale, $img_width);  ?>" />
                    </a>
                <?php } ?>
                <a class="sale_end size-<?php echo "{$size} {$not_current}"; ?> clear no-margin" href="<?php echo $sale->getUrl(); ?>">
                    <h3 class="sale_end_description size-<?php echo $size; ?>">
                        <?php echo  Wonderhop_Sales_Helper_Data::getCountDown($sale); ?>
                    </h3>
                </a>
                <a class="<?php echo $not_current; ?> clear no-margin" href="<?php echo $sale->getUrl(); ?>" title="<?php echo $sale->getName(); ?>">
                    <span class="sale_text sale_text-back sale_text-back-<?php echo ($counter%3)+1; ?> back-<?php echo $current; ?>"><span>
                            <h3 class="sale_title"><?php print $sale->getName(); ?></h3>  
                            <span class="sale_description"><?php print $sale->getSaleDescription(); ?></span>
                    </span></span>
                </a>
            </div>
        </li>
        <?php
        
        $$current .= ob_get_clean();
        $counter++;
    }
    ?>
        
    <div class="sales_section sales_section-<?php echo $class; ?>">
        <div class="page_begin_normal"></div>
        <ul class="sales cat_sales left col-2col cat_sales_left-<?php echo $class; ?>">
            <li class="sales_heading-wrap">
                <h2 class="sales_heading sales_heading-<?php echo $class; ?>">
                    <?php echo $heading; ?>
                </h2>
            </li>
            <?php echo $left; ?>
        </ul>
        <ul class="sales cat_sales right col-2col cat_sales_right-<?php echo $class; ?>">
            <?php echo $right; ?>
        </ul>
        <div class="page_end_normal page_end_sales_page1"></div>
    </div><!-- .sale_section -->
    <?php
}

// cleanup
unset($opening,$left,$right,$mid,$current,$heading,$class,$counter,$sale,$from_time,$to_time,$sales_categories,$interval);





//
// Closing Shops
//

extract($closing);
$sales_categories = $this->getSales( $interval );

if ( ! empty($sales_categories) and count($sales_categories)) {
    
    $left = '';
    $mid = '';
    $right = '';
    $current = 'left';
    $counter = 0;
    $wbig = 410;
    $wsmall = 330;
    $cwidth = 'wsmall';
    
    foreach($sales_categories as $sale) {
        if(isset($interval['today'])) {
            $to_time = strtotime($sale->getEndDate());
            $from_time = strtotime($sale->getStartDate());
            
            if(round(abs($to_time - $from_time) / 3600,2) > 24 && $sale->getEndDate() < date("Y-m-d 23:59:59", Mage::getModel('core/date')->timestamp(time()))) { 
                continue;
            }
        }
        ob_start(); 
        ?>
        
        <li class="sale-wrap">
            <div class="sale">
                <?php if($sale->getThumbnail()) { ?>
                    <a href="<?php echo $sale->getUrl(); ?>" title="<?php echo $sale->getName(); ?>">
                        <img alt="<?php echo $sale->getName(); ?>" src="<?php echo $this->getResizedImage($sale, 290 );  ?>" />
                    </a>
                <?php } ?>
                <a href="<?php echo $sale->getUrl(); ?>" title="<?php echo $sale->getName(); ?>">
                    <span class="sale_text">
                        <h3 class="sale_title"><?php print $sale->getName(); ?></h3>
                    </span>
                </a>
            </div>
        </li>
        <?php
        
        $current = ($counter%3 == 0) ? 'left' : (($counter%3 == 1) ? 'mid' : 'right');
        $$current .= ob_get_clean();
        $counter++;
    }
    ?>
    <?php
    $blank = '<li class="sale-wrap" style="min-height:100px;"></li>';
    $left = ( ! $left) ? $blank : $left;
    $mid = ( ! $mid) ? $blank : $mid;
    $right = ( ! $right) ? $blank : $right;
    ?>
    <div class="sales_section sales_section-<?php echo $class; ?>">
        <div class="page_begin_wide"></div>
        <ul class="sales cat_sales right col-3col cat_sales_right-<?php echo $class; ?>">
            <?php echo $right; ?>
        </ul>
        <div class="sales_heading-wrap">
            <h2 class="sales_heading sales_heading-<?php echo $class; ?>">
                <?php echo $heading; ?>
            </h2>
        </div>
        <ul class="sales cat_sales left col-3col cat_sales_left-<?php echo $class; ?>">
            <?php echo $left; ?>
        </ul>
        <ul class="sales cat_sales left left-mid col-3col cat_sales_mid-<?php echo $class; ?>">
            <?php echo $mid; ?>
        </ul>
        
        <div class="page_end_wide"></div>
    </div><!-- .sale_section -->
    <?php
}






