<?php if ($this->getCustomer()->getEmailConfirmation()): ?>
    <div class="message error">To get your reward credits please confirm your email.</div>
<?php endif; ?>

<?php 
    $sections = $this->getSaleSections(); 
?>

<?php foreach($sections as $heading => $interval) : ?>

    <h2><?php echo $heading; ?></h2>
    <?php $sales_categories = $this->getSales( $interval ); ?>
    <ul class="sales" id="cat_sales">
        <?php $counter = 0; ?>
        <?php foreach($sales_categories as $sale): ?>
            <?php 
                if(isset($interval['today'])) {
                    $to_time = strtotime($sale->getEndDate());
                    $from_time = strtotime($sale->getStartDate());
                    
                    if(round(abs($to_time - $from_time) / 3600,2) > 24 && $sale->getEndDate() < date("Y-m-d 23:59:59", Mage::getModel('core/date')->timestamp(time()))) {
                        continue;
                    }
                }
            ?>
            <li class="<?php echo $counter%2 == 0 ? 'even': 'odd'; ?>">
            <?php $counter++; ?>
            <span class="sale_ends_in">
                      <h3 class="sale_ends_description">
                        <?php echo  Wonderhop_Sales_Helper_Data::getCountDown($sale); ?>
                      </h3>
            </span>
            <?php if($sale->getThumbnail()): ?>
                <a href="<?php echo $sale->getUrl(); ?>" title="<?php echo $sale->getName(); ?>">
                 <img alt="<?php echo $sale->getName(); ?>" src="<?php echo $this->getResizedImage($sale, 400, 400);  ?>" />
                </a>
            <?php endif; ?>
            <a href="<?php echo $sale->getUrl(); ?>" title="<?php echo $sale->getName(); ?>">
                <span class="top_sale_description">
                   <span class="floatLeft">
                      <h3><?php print $sale->getName(); ?></h3>  
                    <span class="sale_small_description"> <?php print $sale->getSaleDescription(); ?></span>
                </span>
            </a>
           </li>
        <?php endforeach; ?>
    </ul>

<?php endforeach; ?>
 
