<?php

$is_home = (Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms' and Mage::getSingleton('cms/page')->getIdentifier() == 'home');
$home_class = $is_home ? ' home' : '';

//error_log(print_r(Mage::registry('curio_nlg_exp'), true));
$nlg = is_object($nlg = Mage::registry('curio_nlg_exp')) ? $nlg : ((object)array('is' => false));
//error_log(print_r($nlg, true));
//error_log((int)$nlg->is);
if ($nlg->is) {
    ?>
    <script type="text/javascript">
        <?php if ( ! $nlg->cookied) { ?>
            document.cookie = '<?php echo $nlg->cookie_name; ?>=1; expires='
                                + (new Date( '<?php echo $nlg->cookie_expire; ?>' )).toGMTString()
                                +';path=/ ';
        <?php } ?>
        <?php if ($is_home) { ?>
            setLocation('/shops');
        <?php } else { ?>
            jQuery('body .wrapper').first().removeClass('invisible');
        <?php } ?>
    </script>
    <?php
    return;
}


$get_email = '';

if (isset($_SESSION['reg_email'])) {
    if ($_SESSION['reg_email'] == '|*EMAIL*|') {
        unset($_SESSION['reg_email']);
    } else {
        $get_email = $_SESSION['reg_email'];
    }
}

if(isset($_GET['email'])) {
    if ($_GET['email'] != '|*EMAIL*|') {
        $get_email =  $_GET['email'];
        $_SESSION['reg_email'] = $get_email;
    }
} 

$is_logged_in = Mage::getSingleton('customer/session')->isLoggedIn();
 
?>


<div class="login_overlay">
<?php if ($is_home) { ?>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('js/jquery.backstretch.min.js'); ?>"></script>
    <script type="text/javascript">
        jQuery.backstretch('<?php echo $this->getSkinUrl('images/sales/login_popup/overlay.jpg'); ?>');
    </script>
    <ul id="home_popup_menu" class="bottom_menu">    
        <li class="hp_menuitem"><a href="contacting:hello#curioroad/com" title="Contact Us" onclick="hcontact(this)">Contact</a></li>
        <li class="hp_menuitem"><a href="http://curioroad.tumblr.com" title="Visit our Blog">Blog</a></li>
        <li class="hp_menuitem"><a href="/about" title="About Us">About</a></li>
        <li class="hp_copyright">CURIO ROAD &copy; 2012</li>
    </ul>
    <script type="text/javascript">
        setTimeout(function(){jQuery('#home_popup_menu').insertBefore('#backstretch');}, 200);
    </script>
<?php } ?>

 <?php  
    $is_sales = 0;
    
    if( Mage::app()->getFrontController()->getRequest()->getRouteName() == 'shops') {
        $is_sales = 1;
     }
     
    $is_gc_email = Mage::registry('gc_prefill');
           
 ?>
<?php if(!$this->email && !$get_email) { ?>
<div class="popup_register block_popup<?php echo $home_class; ?>" style="display:none;">
<div class="block_popup_inner">
        <?php
        $popup_title = 'Wonderful finds <br/>for an inspired life.';
        if (Mage::registry('gc_prefill')) $popup_title = 'Register to redeem <br/>your gift.';
        ?>
        <h1 class="popup_title"><?php echo $popup_title; ?></h1>
        <div class="control_link">
            <a href="#" id="login_link">LOGIN</a>
        </div>
        <div class="popup_content">
            <p class="pc_l pc_l1">Uniquely lovely jewelry, home decor</p> 
            <p class="pc_l pc_l2">and gifts. All at member-only prices.</p>
            <form <?php if($is_sales or $is_gc_email): ?>onSubmit="return false;"<?php endif; ?> action="/shops" method="post" id="register-form1">
                <input type="hidden" value="" name="url" class="document_url"/>
                <div class="content">
                    <ul class="form-list">
                        <li>
                            <!--<label for="email"><?php echo $this->__('Your Email Address') ?> <span class="required">*</span></label> -->
                            <input name="email" title="<?php echo $this->__('Your Email Address') ?>" id="email" type="email" class="input-text required-entry validate-email validate-duplicate" />
                            <script type="text/javascript">(function($){$(function(){
                                var popup_email = '.popup_register .form-list input#email', $e = $(popup_email),
                                    pt = 'Your email address';
                                if ( ! $e || ! $e.length)  return;
                                ( ! $e.val() || ! $e.val().length) && $e.val(pt);
                                $e.focus(function(){ $e.val() == pt && $e.val(''); })
                                    .blur(function(){ ( ! $e.val() || ! $e.val().length) && $e.val(pt); });
                            });})(jQuery);</script>
                        </li>    
                    </ul>       
                </div>
                <div class="actions">
                    <button class="button" onclick="register1Form.submit()" type="submit" name="register" id="become_member">
                        <span><?php echo $this->__('Become a member') ?></span>
                    </button>
                </div>
        </form> 
    </div>
    
    <script type="text/javascript">
        var register1Form = new VarienForm('register-form1', true);
        Validation.add('validate-duplicate','Email has already registered',function(the_field_value){
            var validated = 0;
            
            jQuery.ajax({
                    url: '/sales/index/mailchecker',
                    data: {'email' : jQuery('#email').val()},
                    dataType: 'json',
                    type: 'POST',
                    async: false,
                    success: function(data, text, request) {
                        if (data == 'OK') {
                           validated = 1;
                        }
                    }
            });
            return validated;
        });
        
        
        register1Form.submit = function () {
                jQuery('#registration_email').val(jQuery('#email').val());
                <?php if($is_sales or $is_gc_email): ?>
                    buildBlock('.popup_register_2');
                <?php else: ?>
                    return true; 
                <?php endif; ?>
             return false; 
        }
    </script>
 
</div>

</div>
<?php } ?>


<?php
$prefill_email = '';
if ($get_email) {
    $incoming = Mage::getModel('customer/customer')->setStore( Mage::app()->getStore() )->loadByEmail($get_email);
    if ($incoming->getId()) {
        $prefill_email = $get_email;
    }
}
//error_log('prefill --'.$prefill_email);
?>

<?php if ( ! $prefill_email) { ?>
<div class="popup_register_2 block_popup<?php echo $home_class; ?>"  style="display:none;">
<div class="block_popup_inner">
    <h1 class="popup_title">You're almost there!</h1>
    <div class="popup_content">
        <form action="/customer/account/createpost" method="post" id="register-form" onSubmit="return false;">
            <input name="email" type="hidden" <?php if($this->email): ?> value="<?=$this->email?>" <?php endif; ?> 
            <?php if ($get_email): ?>  value="<?=$get_email?>" <?php endif; ?>  id="registration_email" />
            <input type="hidden" value="<?php if($this->url): ?><?=$this->url ?>" <?php endif; ?>  name="url"/>
            <input name="lastname" type="hidden" value="-"/>    
            <input name="confirmation" type="hidden" id="passconf" value=""/>
            <div class="content">   
                <ul class="form-list">
                    <li>
                        <input name="firstname" value="" title="<?php echo $this->__('First Name') ?>" id="first_name" type="text" class="input-text required-entry" />
                        <script type="text/javascript">(function($){$(function(){
                            var popup_fname = '.popup_register_2 .form-list input#first_name', $e = $(popup_fname),
                                pt = 'Your first name';
                            if ( ! $e || ! $e.length)  return;
                            ( ! $e.val() || ! $e.val().length) && $e.val(pt);
                            $e.focus(function(){ $e.val() == pt && $e.val(''); })
                                .blur(function(){ ( ! $e.val() || ! $e.val().length) && $e.val(pt); });
                        });})(jQuery);</script>
                    </li>
                    <li>
                        <input name="password" type="password" class="input-text required-entry validate-password" id="pass" />
                        <script type="text/javascript">(function($){$(function(){
                            var popup_makepass = '.popup_register_2 .form-list input#pass', $e = $(popup_makepass),
                                pt = 'Create a password',
                                $eover = (($('#cpass_hover').length && $('#cpass_hover'))|| $('<div id="cpass_hover">'+pt+'</div>'));
                            $e.after($eover);
                            $eover.css({position:'relative',height:0,overflow:'visible',top:-32, cursor:'text',left:6,float:'left',clear:'both'});
                            var overpass = function(show) {
                                if (show) {
                                    $eover.css({display:'block', top: ($e.hasClass('validation-failed')) ? -34 : -32 });
                                } else {
                                    $eover.css({display:'none'});
                                }
                            }
                            //console.log($e);
                            if ( ! $e || ! $e.length)  return;
                            ( ! $e.val() || ! $e.val().length) && overpass(true);
                            $eover.click(function(){ $eover.is(':visible') && (overpass() || $e.focus()); });
                            $e.focus(function(){ $eover.is(':visible') && overpass(); })
                                .blur(function(){ ( ! $e.val() || ! $e.val().length) && overpass(true); });
                        });})(jQuery);</script>
                    </li>
                    <li style="padding-top:15px;font-family:Georgia,serif;font-size:11px; color:#6F5F6D; width:478px;margin-top:18px;">
                        <script type="text/javascript">
                            Validation.add( 'validate-register-terms', 'You must check the above box to become a member.', function(val){ return !!val; });             
                        </script>
                        <input id="terms_agreement" type="checkbox" name="terms_agreement" class="terms_agreement validate-register-terms" checked="checked"/>
                        <label style="width:auto;cursor:pointer;line-height:1;padding-top:7px; text-transform:none; font-weight:normal;" for="terms_agreement">I agree to the <a style="text-transform:none;" href="/terms-of-use" target="_blank">Terms of Use</a> and <a style="text-transform:none;" href="/privacy" target="_blank">Privacy Policy</a></label>
                    </li>
                </ul>          
            </div>
            <div class="actions">
                <button class="button" onclick="registerForm.submit()" type="submit" name="register" id="register2"><span><?php echo $this->__('Enter the site') ?></span></button>
            </div>
        </form>
    </div>
    <script type="text/javascript">
        var registerForm = new VarienForm('register-form', true);
        registerForm.submit = function () {
            jQuery('#passconf').val(jQuery('#pass').val());
            <?php if ($is_gc_email) { ?>
                if (this.validator.validate()) {
                    jQuery.ajax({
                        type: 'POST',
                        async: false,
                        url: '/customer/account/createpost/',
                        data: jQuery(this.form).serialize(),
                        success: function (data){ setLocation( window.location.href ); },
                    });
                }
                return false;      
            <?php } ?>
        }
    </script>
     
</div>
</div>
<?php } ?>


<script type="text/javascript">var url = '';  </script>



<div class="popup_login block_popup<?php echo $home_class; ?>"  style="display:none;">
<div class="block_popup_inner">
    <h1 class="popup_title">Login To Shop</h1>
    <div class="control_link">
        <a id="back_to_register" href="<?php echo $this->helper('customer')->getLoginUrl() ?>">Back</a>
    </div>
    <div class="popup_content">
        <form onSubmit="return false;" action="" method="post" id="login-form">
            <input type="hidden" value="" name="url" class="document_url"/>
            <script type="text/javascript">
                jQuery('.document_url').val(document.URL.replace(/^(?:\/\/|[^\/]+)*\//, ""));
            </script>
            <div class="content">
                <ul class="form-list">
                    <li>
                        <!--<label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label> -->
                        <input name="login[username]"  value="<?php echo $prefill_email; ?>" title="Your Email Address" id="login_email" type="text" class="input-text required-entry validate-email" />
                        <script type="text/javascript">(function($){$(function(){
                            var popup_user = '.popup_login .form-list input#login_email', $e = $(popup_user),
                                pt = 'Your Email Address';
                            if ( ! $e || ! $e.length)  return;
                            ( ! $e.val() || ! $e.val().length) && $e.val(pt);
                            $e.focus(function(){ $e.val() == pt && $e.val(''); })
                                .blur(function(){ ( ! $e.val() || ! $e.val().length) && $e.val(pt); });
                        });})(jQuery);</script>
                    </li>
                    <li>
                        <!--<label for="pass">Password<span class="required">*</span></label> -->
                        <input name="login[password]" type="password" class="input-text required-entry validate-password" id="login_pass" />
                        <input type="text" class="input-text required-entry validate-password" id="login_pass-clear" value="Password" style="display:none;"/>
                        <script type="text/javascript">(function($){$(function(){
                            var popup_logpass = '.popup_login .form-list input#login_pass',
                                $e = $(popup_logpass),
                                eh_id = 'login_pass-real',
                                popup_logpass_clear = '.popup_login .form-list input#login_pass-clear',
                                $ec = $(popup_logpass_clear),
                                ec_id = 'login_pass-clear',
                                e_id = 'login_pass';
                            if ( ! $e || ! $e.length || ! $ec || ! $ec.length) return;
                            $ec.hide();
                            if ( ! $e.val() || ! $e.val().length) {
                                $e.attr('id',eh_id);
                                $ec.attr('id',e_id);
                                $e.hide();
                                $ec.show();
                            }
                            $ec.focus(function(){
                                $ec.attr('id',ec_id);
                                $e.attr('id',e_id);
                                $ec.hide();
                                $e.show();
                                $e.focus();
                            });
                            $e.blur(function(){
                                if( ! $e.val() || ! $e.val().length) {
                                    $e.attr('id',eh_id);
                                    $ec.attr('id',e_id);
                                    $e.hide();
                                    $ec.show();
                                }
                            });
                        });})(jQuery);</script>
                    </li>
                    <li style="height:5px;">
                        <input name="conf" type="hidden" class="validate-email-password"/>
                    </li>
                </ul>
            </div>
            <div class="actions">
                <button class="button" onClick="loginForm.submit();" type="submit" name="send" id="send2">
                    <span><?php echo $this->__('Start Browsing') ?></span>
                </button>
            </div>
            <a id="forgot_link" href="#">Forgot Password?</a>
        </form>
    </div><!-- .popup_content -->
    <script type="text/javascript">
        var loginForm = new VarienForm('login-form', true);
         Validation.add('validate-email-password','Email or password incorrect',function(the_field_value){
            var validated = 0;

            jQuery.ajax({
                    url: '/sales/index/loginpost',
                    data: jQuery('#login-form').serialize(),
                    dataType: 'json',
                    type: 'POST',
                    async: false,
                    success: function(data, text, request) {
                        if (data != 'ERR') {
                           window.location = data;
                           validated = 1;
                           url = data;
                           
                        }
                    }
            });
         
            return validated;
        });
        
        
        loginForm.submit = function () {

            
            return false; 
        }
    </script>

</div>

</div>

<?php $pa_key = (string)Mage::getConfig()->getNode('localconf/marketing/perfectaudience/key'); ?>
<?php if ($is_home and ! $is_logged_in and $pa_key) { ?>
<script type="text/javascript">
  (function() {
    window._pa = window._pa || {};
    // _pa.orderId = "myUser@email.com"; // OPTIONAL: include your user's email address or order ID
    _pa.onLoadEvent = "homepage"; // OPTIONAL: name of segment/conversion to be fired on script load
    var pa = document.createElement('script'); pa.type = 'text/javascript'; pa.async = true;
    pa.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + "//tag.perfectaudience.com/serve/<?php echo $pa_key; ?>.js";
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(pa, s);
  })();
</script>
<?php } ?>
