<div class="popup_login" style="display:none">
    <div class="">
        <p>Treat takes you on a daily shopping <br /> 
        journey through fun and creative products <br /> to inspire your home, family and more!</p>
        <p align="center">Join Now</p>
        Your Email Address
        <input type="text" name="email" />
        <button type="submit">Become a member</button>
        <div class="already_member">
            Already a member? <a href="#" id="login_class">Log In</a>
        </div>
    </div>
</div>
