<script type="text/javascript">
//<![CDATA[
    i=0;
    var recipCount  = 1;
    var maxRecip    = 15;
    var baseUrl     = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";
    
    //initial email recipients limitation here and restore in showAddressRecords() every time:
    var counter = maxRecip;

    function remove_recipient(i){
        $('recipients_name'+i).up(2).remove();
        recipCount--;
        if(recipCount<maxRecip && maxRecip != 0) {
            $('add_recipient_button').show();
            $('max_recipient_message').hide();
        }
        enableConfirm();
        return false;
    }

    function add_recipient(){
        ul = $('recipients_options');
        var li_mail = Element.extend(document.createElement("LI"));
        li_mail.addClassName('fields additional-row');
        li_mail.innerHTML = '<p><a href="delete_email" title="<?php echo $this->__('Remove Email') ?>" onclick="remove_recipient('+i+'); return false" class="btn-remove"><?php echo $this->__('Remove Email') ?>"<\/a><\/p>'
        li_mail.innerHTML += '<div class="field"><label for="recipients_name'+i+'" class="required"><em>*<\/em><?php echo $this->__('Name:') ?><\/label><div class="input-box"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name'+i+'" /><\/div>';
        li_mail.innerHTML += '<div class="field"><label for="recipients_email'+i+'" class="required"><em>*<\/em><?php echo $this->__('Email Address:') ?><\/label><div class="input-box"><input name="recipients[email][]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email'+i+'" type="text" class="input-text required-entry validate-email" /><\/div><\/div>';
        i++;
        recipCount++;
        if(recipCount>=maxRecip && maxRecip != 0) {
            $('add_recipient_button').hide();
            $('max_recipient_message').show();
            disableConfirm();
        }

        ul.appendChild(li_mail);
    }
//]]>
</script>

<script type="text/javascript">
    mixpanel.track("Invite friend page");
</script>

<div class="invite-page">
    <h1>Invite your friends. If they join, you and they BOTH get $3</h1>

    <h2>Meet your personal invite link.</h2>
    <input id="personal_link" type="text" readonly="readonly" size="50" value="<?php echo $this->getPersonalLink() ?>" />
    <div class="clear"></div>
    <h2>Share it with friends on Facebook and Twitter.</h2>
    <div class="clear"></div>
    <ul class="social_share">
        <li>
            <div onclick="post_on_wall();" class="fb-share">
                <a name="fb_share" type="icon_link" share_url="<?php echo $this->getPersonalLink(); ?>"></a>
            </div>
        </li>
        <li>
            <div class="twitter-share">
                <a href="http://twitter.com/share/?url=<?php echo $this->getPersonalLink(); ?>" title="Share this on Twitter" id="service-links-twitter" class="service-links-twitter" rel="nofollow" target="_blank"></a>
                <script type="text/javascript">
                    jQuery('.twitter-share a').click(function(event) {
                        var width  = 575,
                            height = 400,
                            left   = (jQuery(window).width()  - width)  / 2,
                            top    = (jQuery(window).height() - height) / 2,
                            url    = this.href,
                            opts   = 'status=1' +
                                     ',width='  + width  +
                                     ',height=' + height +
                                     ',top='    + top    +
                                     ',left='   + left;
                        window.open(url, 'twitte', opts);
                        return false;
                    });
                </script>
            </div>
        </li>
    </ul><!-- .social_share -->
    
    <script type="text/javascript">
        function post_on_wall() {
            url = 'http://www.facebook.com/sharer.php?u=<?php echo $this->getPersonalLink() ?>&t=<?php echo $this->getPersonalLink() ?>';
            window.open(url, "Post on Wall", "width=780, height=410, toolbar=0, scrollbars=0, status=0, resizable=0, location=0, menuBar=0, left=0, top=0");
        }
    </script>
    
    <div class="clear"></div>
    
    <h2>Or send it to some special someones.</h2>
    
    <form action="<?php echo $this->getUrl('*/*/send'); ?>" method="post" id="invitations-form">
      
        <div class="input-box">    
            <input id="cloud_invite_input" class="invite-emails input-text required-entry" size="150" rel="1" type="text" name="emails" value="" />
        </div>
        <div class="buttons-set-invite">
            <button type="submit" title="Proceed to Checkout" class="button"><span><span>Send</span></span></button>
        </div>
    
      
    </form>
    
    <div id="popup-overlay" style="display:none"></div>
        
    <div id="popup-content" style="display:none">
        <div id="close_popup">X</div>
        <div id="import_loader" style="display: none">
            <p>Your Contacts Are Loading</p>
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>" />
        </div>
        <div class="email_addresses" id="ul_email_add" style="display:none;">
            <ul class="form-list address_records_block address_records" id="address_records" style="display:none;">
            </ul>
        </div>
        <div class="buttons-set-invite">
            <button type="button"  style="display:none;" title="Proceed to Checkout" id="select_emails" class="button cloudsponge_select_emails"><span><span>Select</span></span></button>
        </div>
    </div>
        
    <div class="clear"></div>
    
    <p>or</p>
    <p>Pick the lucky ones from your contacts
        <a id="cloudsponge_gmail" href="#" class="cloudsponge_gmail invite-import-gmail">Gmail</a>  
        <a onclick="return cloudsponge.launch('aol');" href="#" class="invite-import-aol">Aol</a> 
        <a id="cloudsponge_yahoo" href="#" class="cloudsponge_yahoo invite-import-yahoo">Yahoo</a>
        <a id="cloudsponge_msn" href="#" class="cloudsponge_msn invite-import-hotmail">Hotmail</a>          
    </p>
         
    <ul id="cloudsponge_emailcounter" style="display:none;">
        <li id="counter_content"></li>
    </ul>
                     
<?php //</div>  // i think this is the one braking the html layout ?>
        
<div class="clear"></div>
     
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('invitations-form', true);
//]]>
</script>
<hr class="invite-hr"/>
    
<?php $invitations = $this->getAllInviters(); ?>
<?php if (count($invitations)): ?>
    <table width="600px" cellpading="0" cellspacing="0" border="1" align="center">
        <thead>
            <tr>
                <th>Email</th>
                <th>Status</th>
            </tr>
        </thead>
        <?php foreach ($invitations as $email => $status) : ?>
            <?php if(!$email): ?>
                <?php continue; ?>
            <?php endif; ?>
            <tr class="<?php echo $status == 0 || $status == 2 || $status == 3 ? 'not_joined' : 'joined' ?>">
                <td align="center" style="text-align:center"><?php echo $email ?></td>
                <td align="center" style="text-align:center">
                    <?php
                    switch($status):
                        case 0:
                            echo 'Not Joined';
                            break;
                        case 2:
                            echo 'Already Registered' ;
                            break;
                        case 1:
                            echo 'Accepted your invitation';
                            break;
                        case 3:
                            echo "Joined from someone else's invite";
                            break;
                    endswitch;
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

</div>


<?php if (Mage::app()->getStore()->isCurrentlySecure()): ?>
    <script type="text/javascript" src="https://api.cloudsponge.com/address_books.js"></script>
<?php else: ?>
    <script type="text/javascript" src="http://api.cloudsponge.com/address_books.js"></script>
<?php endif; ?>

<script type="text/javascript">
var csPageOptions = {
    domain_key:'<?php echo Mage::getStoreConfig("cloudsponge/account/domain_key") ?>',
    textarea_id:'cloud_invite_input',
    afterSubmitContacts: getContactsList
};
function getContactsList(emails)
{
    var list = new Array();
    for(var i = 0; i.emails.length; i++)
    {
         $('cloud_invite_input').value = $('cloud_invite_input').value + ',' + emails[i].primaryEmail();
    }
     
}
</script>
 












