<script type="text/javascript">
    mixpanel.track("Invite friend page");
</script>
<div class="invite-page">
    <h1>Invite your friends. If they join, you and they BOTH get $3</h1>

    <h2>Meet your personal invite link.</h2>
        <input id="personal_link" type="text" readonly="readonly" size="50" value="<?php echo $this->getPersonalLink() ?>" />
        <div class="clear"></div>
    <h2>Share it with friends on Facebook and Twitter.</h2>
<div class="clear"></div>
    <ul class="social_share">
        <li>
            <div onclick="post_on_wall();" class="fb-share"><a name="fb_share" type="icon_link" share_url="<?php echo $this->getPersonalLink(); ?>"></a>
                </div>
        </li>
        <li>
            <div class="twitter-share">
            <a href="http://twitter.com/share/?url=<?php echo $this->getPersonalLink(); ?>" title="Share this on Twitter" id="service-links-twitter" class="service-links-twitter" rel="nofollow" target="_blank"></a>

             <script type="text/javascript">
             jQuery('.twitter-share a').click(function(event) {
                var width  = 575,
                    height = 400,
                    left   = (jQuery(window).width()  - width)  / 2,
                    top    = (jQuery(window).height() - height) / 2,
                    url    = this.href,
                    opts   = 'status=1' +
                             ',width='  + width  +
                             ',height=' + height +
                             ',top='    + top    +
                             ',left='   + left;

                window.open(url, 'twitte', opts);

                return false;
              });</script>
               </div>
        </li>
    </ul>
    <script type="text/javascript">
	                function post_on_wall() {
		                url = 'http://www.facebook.com/sharer.php?u=<?php echo $this->getPersonalLink() ?>&t=<?php echo $this->getPersonalLink() ?>';
		                window.open(url, "Post on Wall", "width=780, height=410, toolbar=0, scrollbars=0, status=0, resizable=0, location=0, menuBar=0, left=0, top=0");
	                }
    </script>
    <div class="clear"></div>
    <h2>Or send it to some special someones.</h2>
    <form action="<?php echo $this->getUrl('*/*/send'); ?>" method="post" id="invitations-form">
      
        <div class="input-box">    
            <input class="invite-emails input-text required-entry" size="150" rel="1" type="text" name="emails" value="" />
        </div>
        <div class="buttons-set-invite">
            <button type="submit" title="Proceed to Checkout" class="button"><span><span>Send</span></span></button>
        </div>
       
    </form>
    <div class="clear"></div>
        <p>or</p>
        <p>Pick the lucky ones from your contacts</p>
     <div class="clear"></div>
     <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('invitations-form', true);
       
    //]]>
    </script>
    <hr class="invite-hr"/>
    
    <?php $invitations = $this->getAllInviters(); ?>
    <?php if (count($invitations)): ?>
        <table width="600px" cellpading="0" cellspacing="0" border="1" align="center">
            <thead>
                <tr>
                    <th>Email</th>
                    <th>Status</th>
                </tr>
            </thead>
            <?php foreach ($invitations as $email => $status) : ?>
                <?php if(!$email): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <tr class="<?php echo $status == 0 || $status == 2 || $status == 3 ? 'not_joined' : 'joined' ?>">
                    <td align="center" style="text-align:center"><?php echo $email ?></td>
                    <td align="center" style="text-align:center">
                    <?php switch($status):
                            case 0:
                                echo 'Not Joined';
                                break;
                            case 2:
                                echo 'Already Registered' ;
                                break;
                            case 1:
                                echo 'Accepted your invitation';
                                break;
                            case 3:
                                echo "Joined from someone else's invite";
                                break;
                          endswitch;
                     ?></td>
                </tr>
            <?php endforeach; ?>
        </table>
     <?php endif; ?>
</div>
















