<?php

$session = Mage::getSingleton('customer/session');
$customer = $session->isLoggedIn() ? $session->getCustomer() : NULL;


?>


<script type="text/javascript">
//<![CDATA[
    i=0;
    var recipCount  = 1;
    var maxRecip    = 15;
    var baseUrl     = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>";
    
    //initial email recipients limitation here and restore in showAddressRecords() every time:
    var counter = maxRecip;

    function remove_recipient(i){
        $('recipients_name'+i).up(2).remove();
        recipCount--;
        if(recipCount<maxRecip && maxRecip != 0) {
            $('add_recipient_button').show();
            $('max_recipient_message').hide();
        }
        enableConfirm();
        return false;
    }

    function add_recipient(){
        ul = $('recipients_options');
        var li_mail = Element.extend(document.createElement("LI"));
        li_mail.addClassName('fields additional-row');
        li_mail.innerHTML = '<p><a href="delete_email" title="<?php echo $this->__('Remove Email') ?>" onclick="remove_recipient('+i+'); return false" class="btn-remove"><?php echo $this->__('Remove Email') ?>"<\/a><\/p>'
        li_mail.innerHTML += '<div class="field"><label for="recipients_name'+i+'" class="required"><em>*<\/em><?php echo $this->__('Name:') ?><\/label><div class="input-box"><input name="recipients[name][]" type="text" class="input-text required-entry" id="recipients_name'+i+'" /><\/div>';
        li_mail.innerHTML += '<div class="field"><label for="recipients_email'+i+'" class="required"><em>*<\/em><?php echo $this->__('Email Address:') ?><\/label><div class="input-box"><input name="recipients[email][]" value="" title="<?php echo $this->__('Email Address') ?>" id="recipients_email'+i+'" type="text" class="input-text required-entry validate-email" /><\/div><\/div>';
        i++;
        recipCount++;
        if(recipCount>=maxRecip && maxRecip != 0) {
            $('add_recipient_button').hide();
            $('max_recipient_message').show();
            disableConfirm();
        }

        ul.appendChild(li_mail);
    }
//]]>
</script>

<script type="text/javascript">
    mixpanel.track("Invite friend page");
</script>

<div class="invite-page">
    <h1 class="invite-title">
    Get up to <span class="withback"><span class="watercolored"></span>$40 to spend</span> on <span class="withback"><span class="logoed"></span><span class="logo-read">Curio Road.</span></span><br/>
    just by inviting your friends!
    </h1>
    
    <div class="reward-sistem-desc">
        <!--<div class="inv-2col left">
            <div class="rews-item">
                <span class="rews-purp">6</span> friends join = <span class="rews-purp">$10 credit</span>
            </div>
            <div class="rews-item">
                <span class="rews-purp">10</span> friends join = <span class="rews-purp">$20 credit</span>
            </div>
        </div>
        <div class="inv-2col right">
            <div class="rews-item">
                <span class="rews-purp">15</span> friends join = <span class="rews-purp">$40 credit</span>
            </div>
            <div class="rews-item">
                <span class="rews-purp">2</span> friends join = <span class="rews-purp">$5 credit</span>
            </div>
        </div>-->
        <div class="rews-3col">
            <div class="rews-item">
                <span class="rews-purp">6</span> friends join = <span class="rews-purp">$10 credit</span>
            </div>
            <div class="rews-item">
                <span class="rews-purp">10</span> friends join = <span class="rews-purp">$20 credit</span>
            </div>
            <div class="rews-item">
                <span class="rews-purp">15</span> friends join = <span class="rews-purp">$40 credit</span>
            </div>
        </div>
    </div>
    
    <div class="invite-sep"></div>
    
    <div class="personal-invite-container">
        <h2>SHARE YOUR PERSONAL INVITE</h2>
        <?php if ($customer) { ?>
        <input id="personal_link" type="text" readonly="readonly" class="input-text" size="50" value="<?php echo $this->getPersonalLink() ?>" />
        <h2 class="social_share-text">SHARE</h2>
        <ul class="social_share">
            <li>
                <div onclick="return GenShare.post_on_wall(this);" class="fb-share">
                    <a id="product-facebook-link-share" href="<?php echo $this->getPersonalLink(); ?>" name="fb_share" type="icon_link" share_url="<?php echo $this->getPersonalLink(); ?>"></a>
                </div>
            </li>
            <li>
                <div class="twitter-share" onclick="return GenShare.tweet_it(this,{'text':' '});">
                    <a href="<?php echo $this->getPersonalLink(); ?>" title="Share this on Twitter" id="product-service-links-twitter" class="service-links-twitter" rel="nofollow" target="_blank"></a>
                </div>
            </li>
        <?php /*
        <li>
            <div class="pin-share" onclick="return GenShare.pin_it(this,{'text':'<?php echo $_product->getShortDescription() ?>','media':'<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(400); ?>'});">
                <a href="<?php echo $fb_comment_url; ?>" title="Share this on Pinterest" rel="nofollow" target="_blank"></a>
            </div>
        </li>
         */ ?>
        </ul>
        
        
        
        
            <form action="/invite-friends/index/sendinvites" method="post" id="invitations-form" style="display:block;overflow:hidden; float:left; clear:left;">
                <div id="invite-links-container">
                    <a id="cloudsponge_gmail" onclick="cloudsponge.launch('gmail');return false;" href="#" class="csicon cloudsponge_gmail invite-import-gmail">Gmail</a>  
                    <a id="cloudsponge_yahoo" onclick="cloudsponge.launch('yahoo');return false;" href="#" class="csicon cloudsponge_yahoo invite-import-yahoo">Yahoo</a>
                    <a id="cloudsponge_msn" onclick="cloudsponge.launch('msn');return false;" href="#" class="csicon cloudsponge_msn invite-import-hotmail">Hotmail</a>
                    <a onclick="return cloudsponge.launch('aol');return false;" href="#" class="csicon invite-import-aol">Aol</a> 
                </div>

                <input type="hidden" id="key" value="" />
                <input id="cloud_invite_input" class="invite-emails input-text required-entry" size="150" rel="1" type="text" name="emails" value="" />
                <button id="cloud_invite_submit" type="submit" title="Send Invite" class="button"><span><span>Send</span></span></button>
                <div id="invitations-sent" style="font-size:14px;color:#FF7268;position:absolute;left:0px;bottom:0px;display:none;">INVITATIONS SENT !</div>
                
                <?php $nonce = md5('curio'.mt_rand(1000, 25888).time()); Mage::getSingleton('customer/session')->setInviteNonce($nonce); ?>
                <input type="hidden" name="nonce" value="<?php echo $nonce; ?>" />
                
            </form>
        
        
            <!-- inite page -->
            <!-- Include these scripts to import address books with CloudSponge -->
            <script type="text/javascript" src="https://api.cloudsponge.com/address_books.js"></script>
            <script type="text/javascript" charset="utf-8">
                var csPageOptions = {
                    domain_key:"<?php echo (string)Mage::getConfig()->getNode('localconf/cloudsponge/key'); ?>",
                    textarea_id:"cloud_invite_input"
                };
                
                (function($){$(function(){
                    $('#cloud_invite_input, .csicon, .elements_container').click(function(ev){
                        ev.stopPropagation();
                    });
                    $('#invitations-form').submit(function(ev,data){
                        $form = $(this);
                        if ( ! $('#cloud_invite_input').val()) return false;
                        $.post($form.attr('action'),$form.serialize(),function(data){
                            resp = null;
                            try {
                                resp = JSON.parse(data);
                            } catch(e) {
                            }
                            if (resp) {
                                if (resp.redirect) {
                                    window.location.href = resp.redirect;
                                    return false;
                                }
                                // mixpanel.track('Invitation send');
                                if (resp.status == 'success') {
                                    $('#invitations-sent').fadeIn('fast').delay(1000).fadeOut('slow');
                                    $('#cloud_invite_input').val('');
                                }
                            }
                            if ( ! resp || ! resp.status || resp.status != 'success') {
                                // @TODO show error message
                            }
                        });
                        ev.preventDefault();
                        return false;
                    });
                    
                    
                    
                });})(jQuery);
            </script>
        
        
        <?php } else { ?>
            
            <h2 style="color:red; font-weight:bold; font-family:Georgia,serif; font-size: 13px; ">You need to be logged in <br/>to access your persoal link!</h2>
        
        <?php } ?>
        
        <div id="gifts" style="">
            <div class="money initial">
                <span>GET STARTED!</span>
            </div>
            <ul class="indicator">
                <li class="i-level i-level-3"><span class="ammount">$40</span><span class="remainder"></span></li>
                <li class="i-level i-level-2"><span class="ammount">$20</span><span class="remainder"></span></li>
                <li class="i-level i-level-1"><span class="ammount">$10</span><span class="remainder"></span></li>
            </ul>
        </div>
        
        <script type="text/javascript">(function($) {
            function friends_invited(fcount)
            {
                //var fc = (fcount > 30) ? 30 : fcount, 
                //    rem = (fc%5) ? (5 - (fc%5)) : 0,
                //    level = parseInt((fc - (rem ? 5 - rem : 0)) /5);
                ////if (fcount < 5) {
                ////    fc = fcount; level = 0; rem = 5-fcount;
                ////}
                //console.log(fc, rem, level);
                //activate_winning(level, rem);
                var fc = (fcount > 15) ? 15 : fcount, rem, level, msg = 0, acls, rcls;
                switch(true) {
                    case (fc <= 6) :
                        rem = 6-fc; level = rem ? 0 : 1; rcls = 'skipper'; break;
                    case (fc <= 10):
                        rem = 10-fc; level = rem ? 1 : 2; rcls = 'skipper'; break;
                    case (fc <= 15):
                        rem = 15-fc; level = rem ? 2 : 3; rcls = 'skipper'; break;
                    default:
                        level = 0; rem = 0;
                }
                activate_winning(level,rem, msg, acls, rcls);
            }
            
            function activate_winning(level, remainder, msg, add_msg_class, rem_msg_class)
            {
                var $cc = $('.i-level-'+level);
                if ( ! $cc.length && level != 0) return;
                show_level(level);
                $('.indicator li').removeClass('current').removeClass('remaining');
                $('.money.initial').removeClass('initial');
                if (remainder && remainder != 0) {
                    var $nc = $('.i-level-'+(level+1));
                    if ( ! $nc.length) return;
                    $('.indicator li').removeClass('remains');
                    $('.remainder',$nc).html(''+remainder+'<br/><span style="color:gray;font-weight:normal;">more</span>');
                    $nc.addClass('remaining');
                    $('.money span').html('+' + remainder + ' INVITES TO ' + $('.ammount',$nc).text().slice(0,5) + '!');
                    if (add_msg_class) { $('.money span').addClass(add_msg_class); $('.ammount',$cc).addClass(add_msg_class); }
                    if (rem_msg_class) { $('.money span').removeClass(rem_msg_class); $('.ammount',$cc).removeClass(rem_msg_class); }
                } else {
                    $cc.addClass('current');
                    msg = msg ? msg : ('YOU\'VE EARNED ' + $('.ammount',$cc).text() + '!');
                    $('.money span').html(msg);
                    //console.log(add_msg_class);
                    //console.log(rem_msg_class);
                    if (add_msg_class) { $('.money span').addClass(add_msg_class); $('.ammount',$cc).addClass(add_msg_class); }
                    if (rem_msg_class) { $('.money span').removeClass(rem_msg_class); $('.ammount',$cc).removeClass(rem_msg_class); }
                }
            }
            
            function show_level(level)
            {
                $('.indicator li').removeClass('active').removeClass('current');
                for(var i=1; i<=level; i++) {
                    var $c = $('.i-level-'+i);
                    if ($c.length) {
                        $c.addClass('active');
                        if (i == level) $c.addClass('current')
                    }
                }
            }
            
            window.activate_winning = activate_winning;
            window.friends_invited = friends_invited;
            window.show_level = show_level;
            
            <?php
            if ( ! $session->isLoggedIn()) { 
                $helper = new Wonderhop_Invitations_Helper_Data;
                $customer = Mage::getSingleton('customer/session')->getCustomer();
                $fcount = $helper->getNumberOfFriends($customer);
                if ($fcount) {
                    ?>$(function(){ friends_invited( <?php echo $fcount; ?> ); }); <?php
                }
            }
            ?>
            
        })(jQuery);</script>
        
    </div>
    
    
    
    <?php /*
    <div class="clear"></div>
    <ul class="social_share">
        <li>
            <div onclick="post_on_wall();" class="fb-share">
                <a name="fb_share" type="icon_link" share_url="<?php echo $this->getPersonalLink(); ?>"></a>
            </div>
        </li>
        <li>
            <div class="twitter-share">
                <a href="http://twitter.com/share/?url=<?php echo $this->getPersonalLink(); ?>" title="Share this on Twitter" id="service-links-twitter" class="service-links-twitter" rel="nofollow" target="_blank"></a>
                <script type="text/javascript">
                    jQuery('.twitter-share a').click(function(event) {
                        var width  = 575,
                            height = 400,
                            left   = (jQuery(window).width()  - width)  / 2,
                            top    = (jQuery(window).height() - height) / 2,
                            url    = this.href,
                            opts   = 'status=1' +
                                     ',width='  + width  +
                                     ',height=' + height +
                                     ',top='    + top    +
                                     ',left='   + left;
                        window.open(url, 'twitte', opts);
                        return false;
                    });
                </script>
            </div>
        </li>
    </ul><!-- .social_share -->
    
    <script type="text/javascript">
        function post_on_wall() {
            url = 'http://www.facebook.com/sharer.php?u=<?php echo $this->getPersonalLink() ?>&t=<?php echo $this->getPersonalLink() ?>';
            window.open(url, "Post on Wall", "width=780, height=410, toolbar=0, scrollbars=0, status=0, resizable=0, location=0, menuBar=0, left=0, top=0");
        }
    </script>
    
    <div class="clear"></div>
    <?php *//*
    <h2>Or send it to some special someones.</h2>
    
    <form action="<?php *///echo $this->getUrl('*/*/send'); ?><?php /*" method="post" id="invitations-form">
      
        <div class="input-box">    
            <input id="cloud_invite_input" class="invite-emails input-text required-entry" size="150" rel="1" type="text" name="emails" value="" />
        </div>
        <div class="buttons-set-invite">
            <button type="submit" title="Proceed to Checkout" class="button"><span><span>Send</span></span></button>
        </div>
    
      
    </form>
    
    <div id="popup-overlay" style="display:none"></div>
        
    <div id="popup-content" style="display:none">
        <div id="close_popup">X</div>
        <div id="import_loader" style="display: none">
            <p>Your Contacts Are Loading</p>
            <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif')?>" />
        </div>
        <div class="email_addresses" id="ul_email_add" style="display:none;">
            <ul class="form-list address_records_block address_records" id="address_records" style="display:none;">
            </ul>
        </div>
        <div class="buttons-set-invite">
            <button type="button"  style="display:none;" title="Proceed to Checkout" id="select_emails" class="button cloudsponge_select_emails"><span><span>Select</span></span></button>
        </div>
    </div>
        
    <div class="clear"></div>
    <?php *//*
    <p>or</p>
    <p>Pick the lucky ones from your contacts
        <a id="cloudsponge_gmail" href="#" class="cloudsponge_gmail invite-import-gmail">Gmail</a>  
        <a onclick="return cloudsponge.launch('aol');" href="#" class="invite-import-aol">Aol</a> 
        <a id="cloudsponge_yahoo" href="#" class="cloudsponge_yahoo invite-import-yahoo">Yahoo</a>
        <a id="cloudsponge_msn" href="#" class="cloudsponge_msn invite-import-hotmail">Hotmail</a>          
    </p>
         
    <ul id="cloudsponge_emailcounter" style="display:none;">
        <li id="counter_content"></li>
    </ul>
    */ ?>
    
<?php //</div>  // i think this is the one braking the html layout ?>
        
<div class="clear"></div>


<?php /*     
<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('invitations-form', true);
//]]>
</script>
    
<?php $invitations = $this->getAllInviters(); ?>
<?php if (count($invitations)): ?>
    <table width="600px" cellpading="0" cellspacing="0" border="1" align="center">
        <thead>
            <tr>
                <th>Email</th>
                <th>Status</th>
            </tr>
        </thead>
        <?php foreach ($invitations as $email => $status) : ?>
            <?php if(!$email): ?>
                <?php continue; ?>
            <?php endif; ?>
            <tr class="<?php echo $status == 0 || $status == 2 || $status == 3 ? 'not_joined' : 'joined' ?>">
                <td align="center" style="text-align:center"><?php echo $email ?></td>
                <td align="center" style="text-align:center">
                    <?php
                    switch($status):
                        case 0:
                            echo 'Not Joined';
                            break;
                        case 2:
                            echo 'Already Registered' ;
                            break;
                        case 1:
                            echo 'Accepted your invitation';
                            break;
                        case 3:
                            echo "Joined from someone else's invite";
                            break;
                    endswitch;
                    ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>

</div>


<?php if (Mage::app()->getStore()->isCurrentlySecure()): ?>
    <script type="text/javascript" src="https://api.cloudsponge.com/address_books.js"></script>
<?php else: ?>
    <script type="text/javascript" src="http://api.cloudsponge.com/address_books.js"></script>
<?php endif; ?>

<script type="text/javascript">
var csPageOptions = {
    domain_key:'<?php echo Mage::getStoreConfig("cloudsponge/account/domain_key") ?>',
    textarea_id:'cloud_invite_input',
    afterSubmitContacts: getContactsList
};
function getContactsList(emails)
{
    var list = new Array();
    for(var i = 0; i.emails.length; i++)
    {
         $('cloud_invite_input').value = $('cloud_invite_input').value + ',' + emails[i].primaryEmail();
    }
     
}
</script>
 



*/?>

</div><?php // invitations page, to be removed ?>







