<div class="toolbar">
    <div class="pager">
        <p class="amount"></p>
        <div class="limiter">
            <label><?php echo $this->__('Filter') ?></label>
            <?php 
            $currentUrl = $this->getCurrentUrl();
            $currentLimit = $this->getCurrentLimit();
            $baseUrl = $this->getBaseUrl();
            $currentFilter = $this->getCurrentFilter();
            ?>
            <form method="POST" action="<?php echo $baseUrl . "supplier/order/index/limit/" . $currentLimit; ?>" name="orderFilter">
                <select class="no-changes" id="filter_status" name="status">
                    <?php foreach($this->getFilterValues() as $key=>$val) {?>
                        <option value="<?php echo $this->__($key);?>" <?php echo ($currentFilter == $key)?"selected = 'selected'":""; ?>><?php echo $this->__($val);?></option>
                    <?php } ?>
                </select>
                <input type="submit" name="filter" value="Filter"/>
            </form>
            <label><?php echo $this->__('Show') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach ($this->getAvailableOrderLimit() as  $_key=>$_limit): ?>
                <option value="<?php echo $baseUrl . "supplier/order/index" . '/limit/' .  $_key; ?>" <?php echo ($currentLimit == $_key)?"selected = 'selected'":""; ?>>
                    <?php echo $_limit ?>
                </option>
            <?php endforeach; ?>
            </select> <?php echo $this->__('per page') ?>
        </div>
        
        <?php
        $pageInfo = Mage::registry("order_page_count");
        $pageCount = $pageInfo["item_count"];
        $lastPage = $pageInfo["last_page"];
        $currentPage = $this->getCurrentPage();
        if (!isset($currentPage)) {$currentPage = '1';}
        $urlRequest = Mage::app()->getFrontController()->getRequest();
        ?>
        <?php if($lastPage > 1): ?>
            <div class="pages">
                <?php echo $this->__('Page:') ?>
                <ol>
                    <?php for ($_page = 1; $_page <= $lastPage; $_page++) {?>
                        <?php if ($currentPage != $_page) {?>
                            <li><a class="supplier_order_page" href="<?php echo $this->getPageUrl($_page); ?>"><?php echo $_page; ?></a></li>
                        <?php }else { echo "<li class='current'>" . $_page . "</li>";} ?>
                    <?php }?>
                </ol>

            </div>
        <?php endif; ?>
    </div>
</div>